# Generated by Django 6.0.5 on 2026-05-13 18:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('blocked', 'Blocked')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='tenants.tenant')),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='tenants.turfground')),
            ],
            options={
                'db_table': 'slots',
                'ordering': ['date', 'start_time'],
                'indexes': [models.Index(fields=['tenant', 'date', 'status'], name='slots_tenant__3effe1_idx'), models.Index(fields=['turf', 'date'], name='slots_turf_id_8ae27f_idx')],
                'unique_together': {('turf', 'date', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='SlotTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_templates', to='tenants.tenant')),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_templates', to='tenants.turfground')),
            ],
            options={
                'db_table': 'slot_templates',
                'unique_together': {('turf', 'day_of_week', 'start_time')},
            },
        ),
    ]
