# Generated by Django 6.0.5 on 2026-05-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='monthly_pass_bookings',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='tenant',
            name='monthly_pass_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
