# Generated by Django 6.0.5 on 2026-05-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenant_monthly_pass_bookings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='razorpay_key_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tenant',
            name='razorpay_key_secret',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
