# Generated by Django 6.0.5 on 2026-05-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_key_id', models.CharField(blank=True, max_length=255)),
                ('razorpay_key_secret', models.CharField(blank=True, max_length=255)),
                ('platform_name', models.CharField(default='TurfBook', max_length=100)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name': 'Global Settings',
                'verbose_name_plural': 'Global Settings',
            },
        ),
    ]
